spring:
  cloud:
    gateway:
      routes:
        - id: Order
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/order/**
          filters:
            - AuthFilter


        - id: ProductService
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/product/**
          filters:
            - AuthFilter

        - id: PaymentService
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/payment/**

        - id: UserService
          uri: lb://USERSERVICE
          predicates:
            - Path=/auth/**